// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8QcKhh0Fjm2C7GWefZbbEEeFwei0ysfY',
    appId: '1:79408381518:web:3eae1d06d6559479bd4d1f',
    messagingSenderId: '79408381518',
    projectId: 'notes-app-42f99',
    authDomain: 'notes-app-42f99.firebaseapp.com',
    storageBucket: 'notes-app-42f99.firebasestorage.app',
    measurementId: 'G-BGBZJB08ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZjXosJw5LGiuTJBz6fRPd4prvPmi-d5M',
    appId: '1:79408381518:android:b324201be2bbbb16bd4d1f',
    messagingSenderId: '79408381518',
    projectId: 'notes-app-42f99',
    storageBucket: 'notes-app-42f99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQLdZDp8DC8GMT-SF1lU-1QOOZP5AUyLw',
    appId: '1:79408381518:ios:c167b21471887e2ebd4d1f',
    messagingSenderId: '79408381518',
    projectId: 'notes-app-42f99',
    storageBucket: 'notes-app-42f99.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQLdZDp8DC8GMT-SF1lU-1QOOZP5AUyLw',
    appId: '1:79408381518:ios:c167b21471887e2ebd4d1f',
    messagingSenderId: '79408381518',
    projectId: 'notes-app-42f99',
    storageBucket: 'notes-app-42f99.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8QcKhh0Fjm2C7GWefZbbEEeFwei0ysfY',
    appId: '1:79408381518:web:c52b2a91b8f25dd4bd4d1f',
    messagingSenderId: '79408381518',
    projectId: 'notes-app-42f99',
    authDomain: 'notes-app-42f99.firebaseapp.com',
    storageBucket: 'notes-app-42f99.firebasestorage.app',
    measurementId: 'G-VYPLHY9NVT',
  );
}
